/**
 * CONTRACT: Supabase Database Row Types
 *
 * These types mirror the Postgres schema defined in data-model.md.
 * They are the shape of rows returned by Supabase queries for the
 * workout session tracking module.
 *
 * In the actual implementation, these will be generated by the
 * Supabase CLI (`supabase gen types typescript`) and should not
 * be manually maintained. This file serves as the contract reference.
 */

// ---------------------------------------------------------------------------
// workout_sessions
// ---------------------------------------------------------------------------

export type WorkoutSessionStatus = 'in_progress' | 'completed' | 'cancelled' | 'discarded'

export interface WorkoutSessionRow {
  id: string
  user_id: string
  status: WorkoutSessionStatus
  started_at: string        // ISO 8601
  finished_at: string | null
  duration_seconds: number | null
  notes: string | null
  source_plan_id: string | null
  source_workout_day_id: string | null
  sync_status: 'synced' | 'pending_sync'
  created_at: string
  updated_at: string
}

export interface WorkoutSessionInsert
  extends Omit<WorkoutSessionRow, 'created_at' | 'updated_at' | 'sync_status'> {
  sync_status?: 'synced' | 'pending_sync'
}

// ---------------------------------------------------------------------------
// session_exercises
// ---------------------------------------------------------------------------

export interface SessionExerciseRow {
  id: string
  session_id: string
  exercise_id: string
  exercise_name_snapshot: string
  display_order: number
  notes: string | null
  was_replaced: boolean
  original_exercise_id: string | null
  created_at: string
}

export type SessionExerciseInsert = Omit<SessionExerciseRow, 'created_at'>

// ---------------------------------------------------------------------------
// set_logs
// ---------------------------------------------------------------------------

export type SetType = 'normal' | 'warmup' | 'dropset'
export type WeightUnit = 'kg' | 'lbs'

export interface SetLogRow {
  id: string
  session_exercise_id: string
  set_number: number
  weight: number | null
  weight_unit: WeightUnit
  reps: number | null
  set_type: SetType
  rpe: number | null
  is_completed: boolean
  is_pr: boolean
  notes: string | null
  logged_at: string       // ISO 8601
}

export type SetLogInsert = SetLogRow

// ---------------------------------------------------------------------------
// personal_records
// ---------------------------------------------------------------------------

export interface PersonalRecordRow {
  id: string
  user_id: string
  exercise_id: string
  max_weight: number
  max_weight_unit: WeightUnit
  achieved_at: string     // ISO 8601
  set_log_id: string | null
  created_at: string
  updated_at: string
}

export interface PersonalRecordUpsert
  extends Omit<PersonalRecordRow, 'id' | 'created_at' | 'updated_at'> {
  id?: string
}
